name: Main workflow

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Publish articles to dev.to
        uses: sinedied/publish-devto@v2
        with:
          devto_key: ${{ secrets.DEVTO_TOKEN }}
          github_token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          files: 'posts/*.md'
          branch: master
          conventional_commits: false
